### ISSUE TITLE
When is onCreate called ?

### ISSUE THREAD

**Issue by Goutte** [satyan/sugar#574] opened 2016-04-10 18:32 UTC
Hello !

I cloned my android project sources to a new machine and tried Android Studio 2.0 (possibly unrelated to my issue), and now my app complains that the tables I'm using do not exist.

I do the calls to `init` and `terminate` in the `onCreate` and `onTerminate` in my application (by extending `SugarApp`), but the database schema is never created on a fresh install on a new emulator.

Can this possibly be due to the new Android SDK ?

I don't understand when or where and by whom the [`onCreate` of `SugarDb`](https://github.com/satyan/sugar/blob/b16e65326aff32a50a08e867c611972d827bbbef/library/src/main/java/com/orm/SugarDb.java#L32) is called. I'm new to Android, I know the OS itself handles the calls to the `onCreate` of my app and activities, but how are the calls to the `SugarDb` event listeners handled ? If the OS calls them, where do `SugarDb` registers itself to the OS ? I can't find it in the source for the life of me and I'm pretty sure that should be done when the app installs itself on the phone.

I have the same "error" (no schema in the database when I first try to access it) on both versions `1.3` and `1.5` of sugardb. It's probably stupid, but I've slept on it twice now and I'm still confused.

It worked fine on my other machine (which now is dead beyond repair after a decade of faithful services).

The whole sources of my learner's app are available here :  https://github.com/Give2Peer/g2p-client-android

(disclaimer : the code WILL hurt your eyes, sorry about that ; I'm learning)

Has anyone managed to run sugardb on the new (2.0) Android Studio ?

**Comment by KB42** [comment] 2016-04-11 08:53
Same here, for me the reason was because of the Gradle 2.0.0 update.

Try to downgrade your Gradle back to 1.5.0 in your project's build.gradle.

**Comment by JonatanSalas** [comment] 2016-04-11 09:28
The problem is around InstantRun feature from Android Studio 2. Now this has been solved by PR satyan/sugar#564. It's not released yet, so the only possible workaround it's to disable InstantRun or use Sugar from master.

**Comment by JonatanSalas** [comment] 2016-04-11 10:56
I will close this issue because it's been solved. If you need anything related to this, please re open it.

**Closed** 2016-04-11 10:56 UTC

**Comment by Goutte** [comment] 2016-04-11 11:25
Thanks for the tip and the pull request ! Will try the master branch.

**Comment by JonatanSalas** [comment] 2016-04-11 11:35
You are welcome! Good luck on it!

**Comment by Goutte** [comment] 2016-04-12 18:48
And if anyone else reads this and needs to switch to master too, I did it with https://jitpack.io but I had to upgrade Gradle to `2.12` too.

Sugar's giving the sweetness, now. :candy:
