### ISSUE TITLE
Getting "SQLite Exception: No such table" when using with MultiDex Support

### ISSUE THREAD

**Issue by PadaliaRushabh** [satyan/sugar#533] opened 2016-02-26 15:32 UTC
This is my application class

```
public class MyApplication extends MultiDexApplication {
    @Override
    public void onCreate() {
        super.onCreate();
        SugarContext.init(getApplicationContext());
    }

    @Override
    public void onTerminate() {
        super.onTerminate();
        SugarContext.terminate();
    }
}
```

My Manifest
```
         <meta-data android:name="DATABASE" android:value="CTP.db" />
         <meta-data android:name="VERSION" android:value="2" />
         <meta-data android:name="QUERY_LOG" android:value="true" />
         <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.anu.canberratrialpass" />
```

**Comment by jonisaa** [comment] 2016-02-26 16:41
Did your model classes have an empty constructor declared?

**Comment by PadaliaRushabh** [comment] 2016-02-27 03:02
Yes, I have a model "Workout" class. It does have an empty constructor.

```
public class Workouts extends SugarRecord {
    int count;
    int totalDistance;
    String totalTime;
    int avgPerformance;
    int totalRating;

    public Workouts(){}

    public  Workouts(int count , int totalDistance , String totalTime, int avgPerformance, int totalRating){
        this.count = count;
        this.totalDistance = totalDistance;
        this.totalTime = totalTime;
        this.avgPerformance = avgPerformance;
        this.totalRating = totalRating;
    }
}
```

**Comment by jonisaa** [comment] 2016-02-27 12:35
Try this.. Extend the SugarApp class and override the method attachBaseContext(). In this method, call: Multidex.install(this). 

Then, add your application class to the AndroidManifest. And rebuild your project. Let me know if this works.

**Comment by PadaliaRushabh** [comment] 2016-02-28 06:14
It gave me the same error again.
This is what I did

```
public class Sugar extends SugarApp {

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

    @Override
    public void onCreate() {
        super.onCreate();
        SugarContext.init(getApplicationContext());
    }

    @Override
    public void onTerminate() {
        super.onTerminate();
        SugarContext.terminate();
    }
}
```


` android:name="com.comp8715.canberratrailpass.Sugar">`

**Comment by ALJazeeraIDP** [comment] 2016-02-28 11:58
I am having same issue.

```
public class UserLikes extends SugarRecord {
    String userName;
    String likedVendorID;

    public UserLikes() {
    }

```

I guess this issue appeared after updating Android Studio 2 Beta 6 and Android SDK. It was working fine with same code before today morning.

**Comment by ALJazeeraIDP** [comment] 2016-02-28 12:40
I am running same code in Android Studio 1.5.1 and it is running absolutely fine. Let's wait for next beta release for android studio 2.0.

**Comment by sibeliusseraphini** [comment] 2016-02-28 14:25
try to clean the project and build again

**Comment by PadaliaRushabh** [comment] 2016-02-29 00:59
I am running android studio 1.5.1 and still have the issue.

**Comment by klepov** [comment] 2016-02-29 20:46
gradle beta6 is to blame

**Comment by jonisaa** [comment] 2016-03-01 11:29
It's not a trouble of Android Studio. There is the same kind of problem like working with eclipse for Java development. All projects generates a debug folder that has got inside all the .class files. However the trouble it's that this folder it isn't always synchronized with the changes that you apply. 

So my advise to you, delete the debug folder and run a gradle clean build command in order to generate a most actual debug folder. 

Don't blame Android Studio 2 guys, It's one of the biggest modifications that they've done to the ide. Nowadays it's better performance than Android Studio 1.5.1 even when being a Beta release. 

Something else. For those who want to run faster builds, go to gradle.properties and add the property

org.gradle.daemon=true

**Comment by johnmurphy01** [comment] 2016-03-01 23:06
I'm having the same issue. We've had Sugar ORM installed in our app for several months. We rolled our app out to a user who has a Motorola RAZR running KitKat(4.4.2). Most of our Sugar models work but one of the database tables isn't getting created and thusly causing the app to crash. After doing some research, it seems that the root cause is due to MultiDex-ing and the class not being in the primary dex file. Is there any way around this? I don't want to have to switch ORM solutions and I don't want to deny KitKat devices from installing our app.

**Comment by ALJazeeraIDP** [comment] 2016-03-02 08:11
@jonisaa I have tried your solution in AS2 Beta 6. It didn't work.

**Comment by alfmatos** [comment] 2016-03-02 10:41
I see a PR merged on Nov 23, which I assume is not on the 1.4 release that adds MultiDex support (loading all dex files) over at d15dff56c8c80dd6994b15ee9ddb7f6fc50a73ea

Has anyone tried with master to see if it works properly?

**Comment by johnmurphy01** [comment] 2016-03-02 14:58
I haven't tried master. I will give it a go and see if it resolves the issue. Would be nice to have a new version (1.5) that includes multidex support though, so that we get Gradle support.

**Comment by johnmurphy01** [comment] 2016-03-02 15:15
It appears the master branch of Sugar ORM does indeed support multidex. My tests on the KitKat device passed and I no longer had issues with the database tables not being created. Again, I would love to have a version 1.5 release. Thanks! @alfmatos for the info!

**Comment by sibeliusseraphini** [comment] 2016-03-02 15:39
@satyan could you release a 1.5 version

**Comment by kakai248** [comment] 2016-03-29 22:28
I'm having this problem even with master. Everything is correct (already read all the other threads and checked everything), it simply doesn't create the table. And I can't turn off multidex or I won't be able to build the app. Any tips?

**Closed** 2016-04-02 21:55 UTC
